### ISSUE TITLE
最新的Gradle中已经集成了apt

### ISSUE THREAD

**Issue by rayliu521** [joyrun/AptPreferences#2]
在Gradle2.2以上的版本中Android Plugin已经集成了apt，如果在Android Studio中使用Java 8，在某些场景如果添加apt则会报错，具体请见[这里](http://stackoverflow.com/questions/38274453/butterknife-8-1-0-not-working-with-jdk-1-8-in-android-studio-2-1-2)，这是ButterKnife在特定的环境下的报错，里面有Jake Wharton的回复。
可否更新一下？具体请参见[这里](https://bitbucket.org/hvisser/android-apt/wiki/Migration)。

**Comment by ghost** [comment]
遇到同样的问题
